sim:
  mode: 'gpu'
params:
  temperature: 0.5
  memory_size_set: [3] 
  options_set: 'letter'

model:
  model_name: "meta-llama/Llama-3.2-3B-Instruct" #"Qwen/Qwen2.5-7B-Instruct" #"microsoft/phi-4" #"deepseek-ai/DeepSeek-R1-Distill-Qwen-32B" #"microsoft/phi-4" ##"meta-llama/Llama-3.1-8B-Instruct" #
  shorthand: "llama32_3B" #"qwen25_7B" #"dsR1_Q32B" #"phi_4"# 
  API_TOKEN: 'YOUR_TOKEN'
  sys_prompt_is_avail: True
  chat_template_is_avail: True
  quantized: True